/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/broadcast/': RouteRecordInfo<'/broadcast/', '/broadcast', Record<never, never>, Record<never, never>>,
    '/clients/': RouteRecordInfo<'/clients/', '/clients', Record<never, never>, Record<never, never>>,
    '/countries/': RouteRecordInfo<'/countries/', '/countries', Record<never, never>, Record<never, never>>,
    '/countries/[id]': RouteRecordInfo<'/countries/[id]', '/countries/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/countries/create': RouteRecordInfo<'/countries/create', '/countries/create', Record<never, never>, Record<never, never>>,
    '/events/': RouteRecordInfo<'/events/', '/events', Record<never, never>, Record<never, never>>,
    '/users/': RouteRecordInfo<'/users/', '/users', Record<never, never>, Record<never, never>>,
    '/whatsapp/': RouteRecordInfo<'/whatsapp/', '/whatsapp', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/auth/login.vue': {
      routes: '/auth/login'
      views: never
    }
    'src/pages/broadcast/index.vue': {
      routes: '/broadcast/'
      views: never
    }
    'src/pages/clients/index.vue': {
      routes: '/clients/'
      views: never
    }
    'src/pages/countries/index.vue': {
      routes: '/countries/'
      views: never
    }
    'src/pages/countries/[id].vue': {
      routes: '/countries/[id]'
      views: never
    }
    'src/pages/countries/create.vue': {
      routes: '/countries/create'
      views: never
    }
    'src/pages/events/index.vue': {
      routes: '/events/'
      views: never
    }
    'src/pages/users/index.vue': {
      routes: '/users/'
      views: never
    }
    'src/pages/whatsapp/index.vue': {
      routes: '/whatsapp/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
